-- Driver Receipts Management System
-- This table tracks receipts generated by drivers for admin monitoring

CREATE TABLE IF NOT EXISTS `driver_receipts` (
  `receipt_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `generated_by` int(11) NOT NULL,
  `status` enum('generated','printed','delivered','cancelled') DEFAULT 'generated',
  `notes` text DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `printed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`receipt_id`),
  KEY `order_id` (`order_id`),
  KEY `generated_by` (`generated_by`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insert sample data for testing
INSERT INTO `driver_receipts` (`receipt_id`, `order_id`, `generated_by`, `status`, `notes`, `delivered_at`, `printed_at`, `created_at`) VALUES
(1, 1, 1, 'delivered', 'Receipt generated by driver for order #000001', NOW(), NOW(), NOW()),
(2, 2, 1, 'printed', 'Receipt generated by driver for order #000002', NULL, NOW(), NOW()),
(3, 3, 1, 'generated', 'Receipt generated by driver for order #000003', NULL, NULL, NOW());
