<?php
require_once '../../config.php';
if (!auth() || !in_array($_SESSION['position'], ['admin', 'driver'])) redirect('login.php');

$pageTitle = 'Driver Receipt Management';
ob_start();

// Get driver stats
$userId = $_SESSION['user_id'];
$today = date('Y-m-d');

// Get recent receipts generated by this driver
$stmt = $db->prepare("
    SELECT 
        dr.*,
        t.payment_id as order_id,
        u.name as customer_name,
        u.phone_number as customer_phone,
        u.email as customer_email,
        pm.method_name as payment_method_name,
        t.total_price,
        t.payment_status,
        t.laundry_status
    FROM driver_receipts dr
    LEFT JOIN transactions t ON dr.order_id = t.payment_id
    LEFT JOIN users u ON t.user_id = u.user_id
    LEFT JOIN payment_methods pm ON t.payment_method_id = pm.method_id
    WHERE dr.generated_by = ?
    ORDER BY dr.created_at DESC
    LIMIT 20
");
$stmt->execute([$userId]);
$recentReceipts = $stmt->fetchAll();

// Get today's receipt count
$stmt = $db->prepare("SELECT COUNT(*) FROM driver_receipts WHERE DATE(created_at) = ? AND generated_by = ?");
$stmt->execute([$today, $userId]);
$todayReceipts = $stmt->fetchColumn();

// Get pending receipts (not yet delivered to customer)
$stmt = $db->prepare("SELECT COUNT(*) FROM driver_receipts WHERE status = 'generated' AND generated_by = ?");
$stmt->execute([$userId]);
$pendingReceipts = $stmt->fetchColumn();
?>

<div class="bg-white rounded-lg shadow-sm p-6">
    <div class="flex justify-between items-center mb-6">
        <div>
            <h2 class="text-2xl font-bold text-gray-800">Receipt Management</h2>
            <p class="text-gray-600">Generate and manage customer receipts</p>
        </div>
        <div class="text-right">
            <p class="text-sm text-gray-500"><?php echo date('l, F j, Y'); ?></p>
            <p class="text-sm text-gray-500"><?php echo date('h:i A'); ?></p>
        </div>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <!-- Today's Receipts -->
        <div class="bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-lg p-6 text-white">
            <div class="flex items-center justify-between mb-4">
                <div class="bg-white bg-opacity-20 p-3 rounded-lg">
                    <i class="fas fa-receipt text-2xl"></i>
                </div>
                <div class="text-right">
                    <i class="fas fa-calendar-day text-2xl opacity-50"></i>
                </div>
            </div>
            <h3 class="text-3xl font-bold mb-1"><?php echo $todayReceipts; ?></h3>
            <p class="text-blue-100 text-sm font-medium">Today's Receipts</p>
        </div>

        <!-- Pending Delivery -->
        <div class="bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl shadow-lg p-6 text-white">
            <div class="flex items-center justify-between mb-4">
                <div class="bg-white bg-opacity-20 p-3 rounded-lg">
                    <i class="fas fa-clock text-2xl"></i>
                </div>
                <div class="text-right">
                    <i class="fas fa-exclamation-triangle text-2xl opacity-50"></i>
                </div>
            </div>
            <h3 class="text-3xl font-bold mb-1"><?php echo $pendingReceipts; ?></h3>
            <p class="text-orange-100 text-sm font-medium">Pending Delivery</p>
        </div>

        <!-- Success Rate -->
        <div class="bg-gradient-to-br from-green-500 to-green-600 rounded-xl shadow-lg p-6 text-white">
            <div class="flex items-center justify-between mb-4">
                <div class="bg-white bg-opacity-20 p-3 rounded-lg">
                    <i class="fas fa-check-circle text-2xl"></i>
                </div>
                <div class="text-right">
                    <i class="fas fa-chart-line text-2xl opacity-50"></i>
                </div>
            </div>
            <h3 class="text-3xl font-bold mb-1">98%</h3>
            <p class="text-green-100 text-sm font-medium">Delivery Success</p>
        </div>
    </div>

    <!-- Quick Actions -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <button onclick="generateReceipt()" class="bg-green-50 hover:bg-green-100 p-6 rounded-lg border border-green-200 transition-colors">
            <div class="flex items-center">
                <i class="fas fa-plus-circle text-3xl text-green-600 mr-4"></i>
                <div>
                    <h3 class="text-lg font-semibold text-gray-800">Generate Receipt</h3>
                    <p class="text-gray-600">Create new receipt</p>
                </div>
            </div>
        </button>
        
        <button onclick="scanOrder()" class="bg-blue-50 hover:bg-blue-100 p-6 rounded-lg border border-blue-200 transition-colors">
            <div class="flex items-center">
                <i class="fas fa-qrcode text-3xl text-blue-600 mr-4"></i>
                <div>
                    <h3 class="text-lg font-semibold text-gray-800">Scan Order</h3>
                    <p class="text-gray-600">QR code scanning</p>
                </div>
            </div>
        </button>
        
        <button onclick="viewPending()" class="bg-orange-50 hover:bg-orange-100 p-6 rounded-lg border border-orange-200 transition-colors">
            <div class="flex items-center">
                <i class="fas fa-list text-3xl text-orange-600 mr-4"></i>
                <div>
                    <h3 class="text-lg font-semibold text-gray-800">Pending Receipts</h3>
                    <p class="text-gray-600">View pending delivery</p>
                </div>
            </div>
        </button>
        
        <button onclick="printBatch()" class="bg-purple-50 hover:bg-purple-100 p-6 rounded-lg border border-purple-200 transition-colors">
            <div class="flex items-center">
                <i class="fas fa-print text-3xl text-purple-600 mr-4"></i>
                <div>
                    <h3 class="text-lg font-semibold text-gray-800">Batch Print</h3>
                    <p class="text-gray-600">Print multiple receipts</p>
                </div>
            </div>
        </button>
    </div>

    <!-- Recent Receipts -->
    <div class="bg-white border border-gray-200 rounded-lg p-6">
        <div class="flex justify-between items-center mb-6">
            <h3 class="text-lg font-semibold text-gray-800">Recent Receipts Generated</h3>
            <button onclick="refreshReceipts()" class="text-blue-500 hover:text-blue-700 text-sm font-medium">
                <i class="fas fa-sync-alt mr-1"></i>Refresh
            </button>
        </div>

        <?php if (empty($recentReceipts)): ?>
            <div class="text-center py-12">
                <i class="fas fa-receipt text-4xl text-gray-300 mb-4"></i>
                <h3 class="text-xl font-semibold text-gray-600 mb-2">No Receipts Generated Yet</h3>
                <p class="text-gray-500 mb-6">Start generating receipts for customers</p>
                <button onclick="generateReceipt()" class="inline-flex items-center bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg font-semibold transition">
                    <i class="fas fa-plus mr-2"></i>Generate First Receipt
                </button>
            </div>
        <?php else: ?>
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead>
                        <tr class="border-b border-gray-200">
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Receipt ID</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Order</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Customer</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Amount</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Status</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Generated</th>
                            <th class="text-left py-3 px-4 font-semibold text-gray-700">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($recentReceipts as $receipt): ?>
                        <tr class="border-b border-gray-100 hover:bg-gray-50">
                            <td class="py-3 px-4">
                                <span class="font-mono text-sm font-bold text-gray-800">#<?php echo str_pad($receipt['receipt_id'], 6, '0', STR_PAD_LEFT); ?></span>
                            </td>
                            <td class="py-3 px-4">
                                <span class="font-mono text-sm font-bold text-blue-600">#<?php echo str_pad($receipt['order_id'], 6, '0', STR_PAD_LEFT); ?></span>
                            </td>
                            <td class="py-3 px-4">
                                <div>
                                    <p class="font-semibold text-gray-800"><?php echo htmlspecialchars($receipt['customer_name']); ?></p>
                                    <p class="text-sm text-gray-500"><?php echo htmlspecialchars($receipt['customer_phone']); ?></p>
                                </div>
                            </td>
                            <td class="py-3 px-4">
                                <span class="font-bold text-green-600">₱<?php echo number_format($receipt['total_price'], 2); ?></span>
                            </td>
                            <td class="py-3 px-4">
                                <?php
                                $statusColors = [
                                    'generated' => ['bg-blue-100', 'text-blue-800'],
                                    'delivered' => ['bg-green-100', 'text-green-800'],
                                    'printed' => ['bg-purple-100', 'text-purple-800'],
                                    'cancelled' => ['bg-red-100', 'text-red-800']
                                ];
                                [$bg, $text] = $statusColors[$receipt['status']] ?? ['bg-gray-100', 'text-gray-800'];
                                ?>
                                <span class="px-2 py-1 rounded-full text-xs font-bold <?php echo $bg; ?> <?php echo $text; ?>">
                                    <?php echo ucfirst($receipt['status']); ?>
                                </span>
                            </td>
                            <td class="py-3 px-4">
                                <span class="text-sm text-gray-600">
                                    <?php echo date('M d, Y h:i A', strtotime($receipt['created_at'])); ?>
                                </span>
                            </td>
                            <td class="py-3 px-4">
                                <div class="flex space-x-2">
                                    <button onclick="viewReceipt(<?php echo $receipt['receipt_id']; ?>)" 
                                            class="text-blue-500 hover:text-blue-700" title="View Receipt">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <button onclick="printReceipt(<?php echo $receipt['receipt_id']; ?>)" 
                                            class="text-green-500 hover:text-green-700" title="Print Receipt">
                                        <i class="fas fa-print"></i>
                                    </button>
                                    <button onclick="markDelivered(<?php echo $receipt['receipt_id']; ?>)" 
                                            class="text-purple-500 hover:text-purple-700" title="Mark Delivered">
                                        <i class="fas fa-check"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>

<!-- Receipt Generation Modal -->
<div id="receiptModal" class="fixed inset-0 bg-black bg-opacity-50 hidden z-50">
    <div class="flex items-center justify-center min-h-screen p-4">
        <div class="bg-white rounded-lg shadow-xl max-w-2xl w-full">
            <div class="p-6">
                <div class="flex justify-between items-center mb-4">
                    <h3 class="text-lg font-semibold text-gray-800">Generate Customer Receipt</h3>
                    <button type="button" id="closeReceiptModal" class="text-gray-400 hover:text-gray-600">
                        <i class="fas fa-times text-xl"></i>
                    </button>
                </div>
                
                <div class="space-y-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Search Order</label>
                        <div class="flex space-x-2">
                            <input type="text" id="orderSearch" placeholder="Enter Order ID or Customer Name..." 
                                   class="flex-1 px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                            <button onclick="searchOrder()" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                    
                    <div id="orderResults" class="space-y-2">
                        <!-- Search results will be loaded here -->
                    </div>
                    
                    <div id="receiptPreview" class="hidden">
                        <h4 class="font-semibold text-gray-800 mb-2">Receipt Preview</h4>
                        <div class="bg-gray-50 p-4 rounded-lg border">
                            <div id="previewContent">
                                <!-- Receipt preview will be loaded here -->
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="flex justify-end space-x-3 mt-6">
                    <button type="button" id="cancelReceipt" class="px-4 py-2 text-gray-600 hover:text-gray-800">
                        Cancel
                    </button>
                    <button onclick="confirmGenerateReceipt()" class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700">
                        <i class="fas fa-receipt mr-2"></i>Generate Receipt
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
let selectedOrderId = null;

// Modal functions
function openReceiptModal() {
    document.getElementById('receiptModal').classList.remove('hidden');
}

function closeReceiptModal() {
    document.getElementById('receiptModal').classList.add('hidden');
    selectedOrderId = null;
    document.getElementById('orderResults').innerHTML = '';
    document.getElementById('receiptPreview').classList.add('hidden');
}

// Event listeners
document.getElementById('closeReceiptModal').addEventListener('click', closeReceiptModal);
document.getElementById('cancelReceipt').addEventListener('click', closeReceiptModal);
document.getElementById('receiptModal').addEventListener('click', function(e) {
    if (e.target === this) closeReceiptModal();
});

// Generate receipt
window.generateReceipt = function() {
    openReceiptModal();
};

// Search order
window.searchOrder = async function() {
    const searchTerm = document.getElementById('orderSearch').value.trim();
    if (!searchTerm) {
        showNotification('Please enter a search term', 'error');
        return;
    }

    try {
        const response = await fetch(`../../api/orders.php?search=${encodeURIComponent(searchTerm)}`);
        const data = await response.json();
        
        if (data.success && data.data.length > 0) {
            displayOrderResults(data.data);
        } else {
            showNotification('No orders found', 'info');
        }
    } catch (error) {
        console.error('Error searching orders:', error);
        showNotification('Error searching orders', 'error');
    }
};

// Display search results
function displayOrderResults(orders) {
    const container = document.getElementById('orderResults');
    container.innerHTML = '';

    orders.forEach(order => {
        const orderDiv = document.createElement('div');
        orderDiv.className = 'p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-blue-50 hover:border-blue-300 transition-colors';
        orderDiv.innerHTML = `
            <div class="flex justify-between items-start">
                <div>
                    <h4 class="font-semibold text-gray-800">Order #${String(order.payment_id).padStart(6, '0')}</h4>
                    <p class="text-sm text-gray-600">Customer: ${order.customer_name}</p>
                    <p class="text-sm text-gray-600">Phone: ${order.customer_phone}</p>
                    <p class="text-sm text-gray-500">Date: ${new Date(order.created_at).toLocaleDateString()}</p>
                </div>
                <div class="text-right">
                    <p class="font-bold text-green-600">₱${parseFloat(order.total_price).toFixed(2)}</p>
                    <p class="text-sm text-gray-500">${order.payment_status}</p>
                </div>
            </div>
        `;
        orderDiv.addEventListener('click', () => {
            selectedOrderId = order.payment_id;
            loadReceiptPreview(order);
            // Remove previous selection
            container.querySelectorAll('.bg-blue-50').forEach(el => el.classList.remove('bg-blue-50', 'border-blue-300'));
            orderDiv.classList.add('bg-blue-50', 'border-blue-300');
        });
        container.appendChild(orderDiv);
    });
}

// Load receipt preview
function loadReceiptPreview(order) {
    const preview = document.getElementById('previewContent');
    preview.innerHTML = `
        <div class="text-center mb-4">
            <h3 class="text-xl font-bold text-gray-800">LaundryPro</h3>
            <p class="text-gray-600">Professional Laundry Services</p>
        </div>
        <div class="space-y-2 text-sm">
            <div class="flex justify-between">
                <span>Receipt #:</span>
                <span class="font-semibold">#${String(order.payment_id).padStart(6, '0')}</span>
            </div>
            <div class="flex justify-between">
                <span>Customer:</span>
                <span class="font-semibold">${order.customer_name}</span>
            </div>
            <div class="flex justify-between">
                <span>Phone:</span>
                <span class="font-semibold">${order.customer_phone}</span>
            </div>
            <div class="flex justify-between">
                <span>Amount:</span>
                <span class="font-bold text-green-600">₱${parseFloat(order.total_price).toFixed(2)}</span>
            </div>
            <div class="flex justify-between">
                <span>Status:</span>
                <span class="font-semibold">${order.payment_status}</span>
            </div>
        </div>
    `;
    document.getElementById('receiptPreview').classList.remove('hidden');
}

// Confirm generate receipt
window.confirmGenerateReceipt = async function() {
    if (!selectedOrderId) {
        showNotification('Please select an order', 'error');
        return;
    }

    try {
        const response = await fetch('../../api/driver_receipts.php', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                action: 'generate',
                order_id: selectedOrderId
            })
        });
        
        const data = await response.json();
        
        if (data.success) {
            showNotification('Receipt generated successfully!', 'success');
            closeReceiptModal();
            location.reload(); // Refresh to show new receipt
        } else {
            showNotification(data.message || 'Error generating receipt', 'error');
        }
    } catch (error) {
        console.error('Error generating receipt:', error);
        showNotification('Error generating receipt', 'error');
    }
};

// View receipt
window.viewReceipt = function(receiptId) {
    window.open(`receipt-viewer.php?id=${receiptId}&type=driver`, '_blank');
};

// Print receipt
window.printReceipt = function(receiptId) {
    window.open(`receipt-viewer.php?id=${receiptId}&type=driver&print=1`, '_blank');
};

// Mark as delivered
window.markDelivered = async function(receiptId) {
    if (!confirm('Mark this receipt as delivered to customer?')) return;

    try {
        const response = await fetch('../../api/driver_receipts.php', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                action: 'mark_delivered',
                receipt_id: receiptId
            })
        });
        
        const data = await response.json();
        
        if (data.success) {
            showNotification('Receipt marked as delivered!', 'success');
            location.reload();
        } else {
            showNotification(data.message || 'Error updating receipt', 'error');
        }
    } catch (error) {
        console.error('Error updating receipt:', error);
        showNotification('Error updating receipt', 'error');
    }
};

// Other functions
window.scanOrder = function() {
    showNotification('QR scanner feature coming soon!', 'info');
};

window.viewPending = function() {
    // Filter to show only pending receipts
    const rows = document.querySelectorAll('tbody tr');
    rows.forEach(row => {
        const statusCell = row.querySelector('td:nth-child(5) span');
        if (statusCell && statusCell.textContent.trim() === 'Generated') {
            row.style.display = '';
        } else {
            row.style.display = 'none';
        }
    });
};

window.printBatch = function() {
    showNotification('Batch print feature coming soon!', 'info');
};

window.refreshReceipts = function() {
    location.reload();
};

// Notification function
function showNotification(message, type = 'info') {
    const notification = document.createElement('div');
    notification.className = `fixed top-4 right-4 p-4 rounded-lg shadow-lg z-50 ${
        type === 'success' ? 'bg-green-500 text-white' :
        type === 'error' ? 'bg-red-500 text-white' :
        type === 'info' ? 'bg-blue-500 text-white' :
        'bg-gray-500 text-white'
    }`;
    notification.textContent = message;
    document.body.appendChild(notification);

    setTimeout(() => {
        notification.remove();
    }, 3000);
}

// Auto-refresh every 30 seconds
setInterval(function() {
    // Only refresh if no modal is open
    if (document.getElementById('receiptModal').classList.contains('hidden')) {
        location.reload();
    }
}, 30000);
</script>

<?php
$content = ob_get_clean();
include '../../layout.php';
?>
