<?php
require_once '../config.php';
require_once '../security_middleware.php';

header('Content-Type: application/json');

// Check authentication
if (!auth()) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

// Check if user is driver or admin
if (!in_array($_SESSION['position'], ['admin', 'driver'])) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Access denied. Driver access required.']);
    exit;
}

$method = $_SERVER['REQUEST_METHOD'];
$input = json_decode(file_get_contents('php://input'), true);

try {
    switch ($method) {
        case 'GET':
            handleGet($input);
            break;
        case 'POST':
            handlePost($input);
            break;
        case 'PUT':
            handlePut($input);
            break;
        case 'DELETE':
            handleDelete($input);
            break;
        default:
            http_response_code(405);
            echo json_encode(['success' => false, 'message' => 'Method not allowed']);
    }
} catch (Exception $e) {
    error_log("Driver receipts API error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Internal server error']);
}

function handleGet($input) {
    global $db;
    
    $userId = $_SESSION['user_id'];
    $action = $_GET['action'] ?? 'list';
    
    switch ($action) {
        case 'list':
            // Get receipts generated by this driver
            $stmt = $db->prepare("
                SELECT 
                    dr.*,
                    t.payment_id as order_id,
                    u.name as customer_name,
                    u.phone_number as customer_phone,
                    u.email as customer_email,
                    pm.method_name as payment_method_name,
                    t.total_price,
                    t.payment_status,
                    t.laundry_status
                FROM driver_receipts dr
                LEFT JOIN transactions t ON dr.order_id = t.payment_id
                LEFT JOIN users u ON t.user_id = u.user_id
                LEFT JOIN payment_methods pm ON t.payment_method_id = pm.method_id
                WHERE dr.generated_by = ?
                ORDER BY dr.created_at DESC
            ");
            $stmt->execute([$userId]);
            $receipts = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            echo json_encode(['success' => true, 'data' => $receipts]);
            break;
            
        case 'stats':
            // Get driver receipt statistics
            $today = date('Y-m-d');
            
            $stmt = $db->prepare("SELECT COUNT(*) FROM driver_receipts WHERE DATE(created_at) = ? AND generated_by = ?");
            $stmt->execute([$today, $userId]);
            $todayReceipts = $stmt->fetchColumn();
            
            $stmt = $db->prepare("SELECT COUNT(*) FROM driver_receipts WHERE status = 'generated' AND generated_by = ?");
            $stmt->execute([$userId]);
            $pendingReceipts = $stmt->fetchColumn();
            
            $stmt = $db->prepare("SELECT COUNT(*) FROM driver_receipts WHERE status = 'delivered' AND generated_by = ?");
            $stmt->execute([$userId]);
            $deliveredReceipts = $stmt->fetchColumn();
            
            echo json_encode([
                'success' => true,
                'data' => [
                    'today_receipts' => $todayReceipts,
                    'pending_receipts' => $pendingReceipts,
                    'delivered_receipts' => $deliveredReceipts
                ]
            ]);
            break;
            
        default:
            http_response_code(400);
            echo json_encode(['success' => false, 'message' => 'Invalid action']);
    }
}

function handlePost($input) {
    global $db;
    
    $action = $input['action'] ?? '';
    $userId = $_SESSION['user_id'];
    
    switch ($action) {
        case 'generate':
            generateReceipt($input, $userId);
            break;
        case 'mark_delivered':
            markReceiptDelivered($input, $userId);
            break;
        case 'print':
            markReceiptPrinted($input, $userId);
            break;
        default:
            http_response_code(400);
            echo json_encode(['success' => false, 'message' => 'Invalid action']);
    }
}

function generateReceipt($input, $userId) {
    global $db;
    
    $orderId = $input['order_id'] ?? null;
    
    if (!$orderId) {
        echo json_encode(['success' => false, 'message' => 'Order ID is required']);
        return;
    }
    
    // Check if order exists and is valid
    $stmt = $db->prepare("
        SELECT t.*, u.name as customer_name, u.phone_number as customer_phone
        FROM transactions t
        LEFT JOIN users u ON t.user_id = u.user_id
        WHERE t.payment_id = ?
    ");
    $stmt->execute([$orderId]);
    $order = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$order) {
        echo json_encode(['success' => false, 'message' => 'Order not found']);
        return;
    }
    
    // Check if receipt already exists
    $stmt = $db->prepare("SELECT receipt_id FROM driver_receipts WHERE order_id = ?");
    $stmt->execute([$orderId]);
    if ($stmt->fetch()) {
        echo json_encode(['success' => false, 'message' => 'Receipt already exists for this order']);
        return;
    }
    
    // Generate receipt
    $stmt = $db->prepare("
        INSERT INTO driver_receipts (order_id, generated_by, status, notes, created_at) 
        VALUES (?, ?, 'generated', ?, NOW())
    ");
    
    $notes = "Receipt generated by driver for order #" . str_pad($orderId, 6, '0', STR_PAD_LEFT);
    
    if ($stmt->execute([$orderId, $userId, $notes])) {
        $receiptId = $db->lastInsertId();
        
        // Log the action
        $stmt = $db->prepare("
            INSERT INTO user_logs (user_id, action, details, ip_address, user_agent) 
            VALUES (?, 'receipt_generated', ?, ?, ?)
        ");
        $stmt->execute([
            $userId,
            "Generated receipt #{$receiptId} for order #{$orderId}",
            $_SERVER['REMOTE_ADDR'] ?? 'unknown',
            $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
        ]);
        
        echo json_encode([
            'success' => true,
            'message' => 'Receipt generated successfully',
            'data' => ['receipt_id' => $receiptId]
        ]);
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to generate receipt']);
    }
}

function markReceiptDelivered($input, $userId) {
    global $db;
    
    $receiptId = $input['receipt_id'] ?? null;
    
    if (!$receiptId) {
        echo json_encode(['success' => false, 'message' => 'Receipt ID is required']);
        return;
    }
    
    // Check if receipt exists and belongs to this driver
    $stmt = $db->prepare("SELECT * FROM driver_receipts WHERE receipt_id = ? AND generated_by = ?");
    $stmt->execute([$receiptId, $userId]);
    $receipt = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$receipt) {
        echo json_encode(['success' => false, 'message' => 'Receipt not found or access denied']);
        return;
    }
    
    // Update receipt status
    $stmt = $db->prepare("
        UPDATE driver_receipts 
        SET status = 'delivered', delivered_at = NOW(), updated_at = NOW()
        WHERE receipt_id = ?
    ");
    
    if ($stmt->execute([$receiptId])) {
        // Log the action
        $stmt = $db->prepare("
            INSERT INTO user_logs (user_id, action, details, ip_address, user_agent) 
            VALUES (?, 'receipt_delivered', ?, ?, ?)
        ");
        $stmt->execute([
            $userId,
            "Marked receipt #{$receiptId} as delivered",
            $_SERVER['REMOTE_ADDR'] ?? 'unknown',
            $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
        ]);
        
        echo json_encode(['success' => true, 'message' => 'Receipt marked as delivered']);
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to update receipt']);
    }
}

function markReceiptPrinted($input, $userId) {
    global $db;
    
    $receiptId = $input['receipt_id'] ?? null;
    
    if (!$receiptId) {
        echo json_encode(['success' => false, 'message' => 'Receipt ID is required']);
        return;
    }
    
    // Check if receipt exists and belongs to this driver
    $stmt = $db->prepare("SELECT * FROM driver_receipts WHERE receipt_id = ? AND generated_by = ?");
    $stmt->execute([$receiptId, $userId]);
    $receipt = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$receipt) {
        echo json_encode(['success' => false, 'message' => 'Receipt not found or access denied']);
        return;
    }
    
    // Update receipt status
    $stmt = $db->prepare("
        UPDATE driver_receipts 
        SET status = 'printed', printed_at = NOW(), updated_at = NOW()
        WHERE receipt_id = ?
    ");
    
    if ($stmt->execute([$receiptId])) {
        // Log the action
        $stmt = $db->prepare("
            INSERT INTO user_logs (user_id, action, details, ip_address, user_agent) 
            VALUES (?, 'receipt_printed', ?, ?, ?)
        ");
        $stmt->execute([
            $userId,
            "Marked receipt #{$receiptId} as printed",
            $_SERVER['REMOTE_ADDR'] ?? 'unknown',
            $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
        ]);
        
        echo json_encode(['success' => true, 'message' => 'Receipt marked as printed']);
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to update receipt']);
    }
}

function handlePut($input) {
    // Update receipt functionality
    echo json_encode(['success' => false, 'message' => 'PUT method not implemented']);
}

function handleDelete($input) {
    // Delete receipt functionality (admin only)
    echo json_encode(['success' => false, 'message' => 'DELETE method not implemented']);
}
?>
